@hostname = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQ1Nzg5OTR9.HKvTN-K6oKnIz3TDHS2Snoc6w3cpHstGsnQuUn6hUEM

#user create
POST {{hostname}}/users
Content-Type: application/json

{
  "name" : "test", 
  "email": "test@gmail.com",
  "age_group": "18-35",
  "password": "password",
  "password_confirmation": "password",
  "location": "Miami, FL",
  "diagnosis_date": "12/01/2000",
  "image_url": "https://images.unsplash.com/flagged/photo-1595514191830-3e96a518989b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80"

}
### users show
GET {{hostname}}/users/2

### user update
PATCH  {{hostname}}/users/6
Content-Type: application/json

{
 "password": "password",
  "diagnosis_date": "2021-02-28"
}

### user delete
DELETE {{hostname}}/users/7

### sessions create (login)
POST {{hostname}}/sessions
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "email" : "blue_s@gmail.com", 
  "password": "password"
}

### groups index
GET {{hostname}}/groups
Content-Type: application/json

### group create
POST {{hostname}}/groups
Content-Type: application/json

{
  "name" : "Strong Women With MS",
  "summary" : "Group of women with MS supporting other women with MS",
  "location" : " Ft. Lauderdale,FL / Virtual",
  "image_url": "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1470&q=80"

}

### group show


### group update- (update group 2 summary)

###group destroy

