@hostname = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQ1Nzg5OTR9.HKvTN-K6oKnIz3TDHS2Snoc6w3cpHstGsnQuUn6hUEM

#user create
POST {{hostname}}/users
Content-Type: application/json

{
  "name" : "test", 
  "email": "test@gmail.com",
  "age_group": "18-35",
  "password": "password",
  "password_confirmation": "password",
  "location": "Miami, FL",
  "diagnosis_date": "12/01/2000",
  "image_url": "https://images.unsplash.com/flagged/photo-1595514191830-3e96a518989b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80"

}
### users show- should only see there own account
GET {{hostname}}/users/2
Authorization: Bearer {{jwt}}


### user update- can only update their own account
PATCH  {{hostname}}/users/6
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
 "password": "password",
  "diagnosis_date": "2021-02-28"
}

### user delete- can only delete their own account
DELETE {{hostname}}/users/7
Authorization: Bearer {{jwt}}

### sessions create (login)
POST {{hostname}}/sessions
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "email" : "blue_s@gmail.com", 
  "password": "password"
}

### groups index
GET {{hostname}}/groups
Content-Type: application/json

### group create
POST {{hostname}}/groups
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name" : "Strong Women With MS",
  "summary" : "Group of women with MS supporting other women with MS",
  "location" : " Ft. Lauderdale,FL / Virtual",
  "image_url": "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1470&q=80"

}

### groups show
GET {{hostname}}/groups/2
Content-Type: application/json
Authorization: Bearer {{jwt}}

### group update-only group admin can update
PATCH {{hostname}}/groups/2
Content-Type: application/json

{
  "summary": "Group of women with MS supporting other women with MS"
}

###group destroy- When a group get's destroyed, users should no longer be assigned to that group
DELETE {{hostname}}/groups/1

### user_group create
POST {{hostname}}/user_groups
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 1,
  "group_id": 2 
  }

### user_group destroy-only when logged in
DELETE {{hostname}}/user_groups/1

### message create- only when logged in
POST {{hostname}}/messages
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 1,
  "group_id": 2,
  "body": "Let's make today a GREAT day!"
}

### message destroy- only users who are logged in and group admin
DELETE {{hostname}}/messages/1
Authorization: Bearer {{jwt}}