@hostname = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjM1MzY5MjY3fQ.yWt-BLS4sa9siKle5IzAPdkMcsy1yaulgJ5qUKiGNM4

#user create (sign up)
POST {{hostname}}/users
Content-Type: application/json

{
  "name" : "Sam Smith", 
  "email": "Sammmy@yahoo.com",
  "age_group": "51+",
  "password": "password",
  "password_confirmation": "password",
  "location": "Dallas, TX",
  "diagnosis_date": "2000-11-12",
  "image_url": "https://images.unsplash.com/flagged/photo-1595514191830-3e96a518989b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=387&q=80"

}
### users show- should only see there own account
GET {{hostname}}/users/10
Content-Type: application/json
Authorization: Bearer {{jwt}}


### user update- can only update their own account
PATCH  {{hostname}}/users/10
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "password": "password123",
  "password_confirmation" :"password123"
}

### user delete- can only delete their own account
DELETE {{hostname}}/users/11
Authorization: Bearer {{jwt}}

### sessions create (login)
POST {{hostname}}/sessions
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "email" : "Sammmy@yahoo.com", 
  "password": "password"
}

### groups index
GET {{hostname}}/groups
Content-Type: application/json

### group create
POST {{hostname}}/groups
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name" : "MS Sucks",
  "summary" : "People with MS doing their best",
  "location" : "Orlando, FL",
  "image_url": ""

}

### groups show
GET {{hostname}}/groups/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### group update-only group admin can update
PATCH {{hostname}}/groups/13
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  
  "image_url": "https://images.unsplash.com/photo-1580855014124-d1e9d454c6b1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2070&q=80"
}

###group destroy
DELETE {{hostname}}/groups/13
Authorization: Bearer {{jwt}}

### user_group create- a user can only join a group when they are logged in
POST {{hostname}}/user_groups
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  
  "group_id": 12
  }

### user_group destroy-only when logged in can a user leave a group
DELETE {{hostname}}/user_groups/13
Authorization: Bearer {{jwt}}

### message create- only when logged in
POST {{hostname}}/messages
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  
  "group_id": 12,
  "body": "Hello everyone!"
}

### message destroy- only users who are logged in and group admin
DELETE {{hostname}}/messages/10
Authorization: Bearer {{jwt}}

### News API Endpoint
GET https://newsapi.org/v2/everything?q=multiple+sclerosis
Authorization: <API KEY>

###

#Rails App Articles Index
GET http://localhost:3000/articles?search=multiple+sclerosis

###

#Quotable API Endpoint
GET https://api.quotable.io/random?tags=wisdom
###

#Rails App Quotes Index
GET http://localhost:3000/quotes?random